Project 4

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 1000)
from datetime import datetime as dt
import matplotlib

In [3]:
df = pd.read_csv('../Data/zillow_data.csv')
df

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
0,84654,60657,Chicago,IL,Chicago,Cook,1,334200.0,335400.0,336500.0,...,1005500,1007500,1007800,1009600,1013300,1018700,1024400,1030700,1033800,1030600
1,90668,75070,McKinney,TX,Dallas-Fort Worth,Collin,2,235700.0,236900.0,236700.0,...,308000,310000,312500,314100,315000,316600,318100,319600,321100,321800
2,91982,77494,Katy,TX,Houston,Harris,3,210400.0,212200.0,212200.0,...,321000,320600,320200,320400,320800,321200,321200,323000,326900,329900
3,84616,60614,Chicago,IL,Chicago,Cook,4,498100.0,500900.0,503100.0,...,1289800,1287700,1287400,1291500,1296600,1299000,1302700,1306400,1308500,1307000
4,93144,79936,El Paso,TX,El Paso,El Paso,5,77300.0,77300.0,77300.0,...,119100,119400,120000,120300,120300,120300,120300,120500,121000,121500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14718,58333,1338,Ashfield,MA,Greenfield Town,Franklin,14719,94600.0,94300.0,94000.0,...,216800,217700,218600,218500,218100,216400,213100,209800,209200,209300
14719,59107,3293,Woodstock,NH,Claremont,Grafton,14720,92700.0,92500.0,92400.0,...,202100,208400,212200,215200,214300,213100,213700,218300,222700,225800
14720,75672,40404,Berea,KY,Richmond,Madison,14721,57100.0,57300.0,57500.0,...,121800,122800,124600,126700,128800,130600,131700,132500,133000,133400
14721,93733,81225,Mount Crested Butte,CO,NaN,Gunnison,14722,191100.0,192400.0,193700.0,...,662800,671200,682400,695600,695500,694700,706400,705300,681500,664400
14722,95851,89155,Mesquite,NV,Las Vegas,Clark,14723,176400.0,176300.0,176100.0,...,333800,336400,339700,343800,346800,348900,350400,353000,356000,357200

In [4]:
df.columns[:100]

Index(['RegionID', 'RegionName', 'City', 'State', 'Metro', 'CountyName',
       'SizeRank', '1996-04', '1996-05', '1996-06', '1996-07', '1996-08',
       '1996-09', '1996-10', '1996-11', '1996-12', '1997-01', '1997-02',
       '1997-03', '1997-04', '1997-05', '1997-06', '1997-07', '1997-08',
       '1997-09', '1997-10', '1997-11', '1997-12', '1998-01', '1998-02',
       '1998-03', '1998-04', '1998-05', '1998-06', '1998-07', '1998-08',
       '1998-09', '1998-10', '1998-11', '1998-12', '1999-01', '1999-02',
       '1999-03', '1999-04', '1999-05', '1999-06', '1999-07', '1999-08',
       '1999-09', '1999-10', '1999-11', '1999-12', '2000-01', '2000-02',
       '2000-03', '2000-04', '2000-05', '2000-06', '2000-07', '2000-08',
       '2000-09', '2000-10', '2000-11', '2000-12', '2001-01', '2001-02',
       '2001-03', '2001-04', '2001-05', '2001-06', '2001-07', '2001-08',
       '2001-09', '2001-10', '2001-11', '2001-12', '2002-01', '2002-02',
       '2002-03', '2002-04', '2002-05', '2002-06', '2002-07', '2002-08',
       '2002-09', '2002-10', '2002-11', '2002-12', '2003-01', '2003-02',
       '2003-03', '2003-04', '2003-05', '2003-06', '2003-07', '2003-08',
       '2003-09', '2003-10', '2003-11', '2003-12'],
      dtype='object')

In [5]:
df.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14723 entries, 0 to 14722
Data columns (total 272 columns):
 #   Column      Dtype
---  ------      -----
 0   RegionID    int64
 1   RegionName  int64
 2   City        object
 3   State       object
 4   Metro       object
 5   CountyName  object
 6   SizeRank    int64
 7   1996-04     float64
 8   1996-05     float64
 9   1996-06     float64
 10  1996-07     float64
 11  1996-08     float64
 12  1996-09     float64
 13  1996-10     float64
 14  1996-11     float64
 15  1996-12     float64
 16  1997-01     float64
 17  1997-02     float64
 18  1997-03     float64
 19  1997-04     float64
 20  1997-05     float64
 21  1997-06     float64
 22  1997-07     float64
 23  1997-08     float64
 24  1997-09     float64
 25  1997-10     float64
 26  1997-11     float64
 27  1997-12     float64
 28  1998-01     float64
 29  1998-02     float64
 30  1998-03     float64
 31  1998-04     float64
 32  1998-05     float64
 33  1998-06     float64
 34  1998-07     float64
 35  1998-08     float64
 36  1998-09     float64
 37  1998-10     float64
 38  1998-11     float64
 39  1998-12     float64
 40  1999-01     float64
 41  1999-02     float64
 42  1999-03     float64
 43  1999-04     float64
 44  1999-05     float64
 45  1999-06     float64
 46  1999-07     float64
 47  1999-08     float64
 48  1999-09     float64
 49  1999-10     float64
 50  1999-11     float64
 51  1999-12     float64
 52  2000-01     float64
 53  2000-02     float64
 54  2000-03     float64
 55  2000-04     float64
 56  2000-05     float64
 57  2000-06     float64
 58  2000-07     float64
 59  2000-08     float64
 60  2000-09     float64
 61  2000-10     float64
 62  2000-11     float64
 63  2000-12     float64
 64  2001-01     float64
 65  2001-02     float64
 66  2001-03     float64
 67  2001-04     float64
 68  2001-05     float64
 69  2001-06     float64
 70  2001-07     float64
 71  2001-08     float64
 72  2001-09     float64
 73  2001-10     float64
 74  2001-11     float64
 75  2001-12     float64
 76  2002-01     float64
 77  2002-02     float64
 78  2002-03     float64
 79  2002-04     float64
 80  2002-05     float64
 81  2002-06     float64
 82  2002-07     float64
 83  2002-08     float64
 84  2002-09     float64
 85  2002-10     float64
 86  2002-11     float64
 87  2002-12     float64
 88  2003-01     float64
 89  2003-02     float64
 90  2003-03     float64
 91  2003-04     float64
 92  2003-05     float64
 93  2003-06     float64
 94  2003-07     float64
 95  2003-08     float64
 96  2003-09     float64
 97  2003-10     float64
 98  2003-11     float64
 99  2003-12     float64
 100 2004-01     float64
 101 2004-02     float64
 102 2004-03     float64
 103 2004-04     float64
 104 2004-05     float64
 105 2004-06     float64
 106 2004-07     float64
 107 2004-08     float64
 108 2004-09     float64
 109 2004-10     float64
 110 2004-11     float64
 111 2004-12     float64
 112 2005-01     float64
 113 2005-02     float64
 114 2005-03     float64
 115 2005-04     float64
 116 2005-05     float64
 117 2005-06     float64
 118 2005-07     float64
 119 2005-08     float64
 120 2005-09     float64
 121 2005-10     float64
 122 2005-11     float64
 123 2005-12     float64
 124 2006-01     float64
 125 2006-02     float64
 126 2006-03     float64
 127 2006-04     float64
 128 2006-05     float64
 129 2006-06     float64
 130 2006-07     float64
 131 2006-08     float64
 132 2006-09     float64
 133 2006-10     float64
 134 2006-11     float64
 135 2006-12     float64
 136 2007-01     float64
 137 2007-02     float64
 138 2007-03     float64
 139 2007-04     float64
 140 2007-05     float64
 141 2007-06     float64
 142 2007-07     float64
 143 2007-08     float64
 144 2007-09     float64
 145 2007-10     float64
 146 2007-11     float64
 147 2007-12     float64
 148 2008-01     float64
 149 2008-02     float64
 150 2008-03     float64
 151 2008-04     float64
 152 2008-05     float64
 153 2008-06     float64
 154 2008-07     float64
 155 2008-08     float64
 156 2008-09     float64
 157 2008-10     float64
 158 2008-11     float64
 159 2008-12     float64
 160 2009-01     float64
 161 2009-02     float64
 162 2009-03     float64
 163 2009-04     float64
 164 2009-05     float64
 165 2009-06     float64
 166 2009-07     float64
 167 2009-08     float64
 168 2009-09     float64
 169 2009-10     float64
 170 2009-11     float64
 171 2009-12     float64
 172 2010-01     float64
 173 2010-02     float64
 174 2010-03     float64
 175 2010-04     float64
 176 2010-05     float64
 177 2010-06     float64
 178 2010-07     float64
 179 2010-08     float64
 180 2010-09     float64
 181 2010-10     float64
 182 2010-11     float64
 183 2010-12     float64
 184 2011-01     float64
 185 2011-02     float64
 186 2011-03     float64
 187 2011-04     float64
 188 2011-05     float64
 189 2011-06     float64
 190 2011-07     float64
 191 2011-08     float64
 192 2011-09     float64
 193 2011-10     float64
 194 2011-11     float64
 195 2011-12     float64
 196 2012-01     float64
 197 2012-02     float64
 198 2012-03     float64
 199 2012-04     float64
 200 2012-05     float64
 201 2012-06     float64
 202 2012-07     float64
 203 2012-08     float64
 204 2012-09     float64
 205 2012-10     float64
 206 2012-11     float64
 207 2012-12     float64
 208 2013-01     float64
 209 2013-02     float64
 210 2013-03     float64
 211 2013-04     float64
 212 2013-05     float64
 213 2013-06     float64
 214 2013-07     float64
 215 2013-08     float64
 216 2013-09     float64
 217 2013-10     float64
 218 2013-11     float64
 219 2013-12     float64
 220 2014-01     float64
 221 2014-02     float64
 222 2014-03     float64
 223 2014-04     float64
 224 2014-05     float64
 225 2014-06     float64
 226 2014-07     int64
 227 2014-08     int64
 228 2014-09     int64
 229 2014-10     int64
 230 2014-11     int64
 231 2014-12     int64
 232 2015-01     int64
 233 2015-02     int64
 234 2015-03     int64
 235 2015-04     int64
 236 2015-05     int64
 237 2015-06     int64
 238 2015-07     int64
 239 2015-08     int64
 240 2015-09     int64
 241 2015-10     int64
 242 2015-11     int64
 243 2015-12     int64
 244 2016-01     int64
 245 2016-02     int64
 246 2016-03     int64
 247 2016-04     int64
 248 2016-05     int64
 249 2016-06     int64
 250 2016-07     int64
 251 2016-08     int64
 252 2016-09     int64
 253 2016-10     int64
 254 2016-11     int64
 255 2016-12     int64
 256 2017-01     int64
 257 2017-02     int64
 258 2017-03     int64
 259 2017-04     int64
 260 2017-05     int64
 261 2017-06     int64
 262 2017-07     int64
 263 2017-08     int64
 264 2017-09     int64
 265 2017-10     int64
 266 2017-11     int64
 267 2017-12     int64
 268 2018-01     int64
 269 2018-02     int64
 270 2018-03     int64
 271 2018-04     int64
dtypes: float64(219), int64(49), object(4)
memory usage: 30.6+ MB

In [14]:
len(df['RegionID'].unique()) # all unique values

14723

In [16]:
len(df['RegionName'].unique()) # all unique values

14723

In [41]:
df['City'].value_counts()[:30]

New York         114
Los Angeles       95
Houston           88
San Antonio       48
Washington        45
Chicago           41
Austin            40
Springfield       40
Columbus          38
Philadelphia      38
Las Vegas         38
Phoenix           37
Kansas City       37
Dallas            35
Portland          34
San Diego         33
Louisville        32
Denver            30
Oklahoma City     30
Omaha             30
Arlington         29
Jacksonville      28
San Jose          27
Richmond          27
Fort Worth        26
Indianapolis      26
Lincoln           25
Charlotte         25
Lexington         25
Franklin          25
Name: City, dtype: int64

In [39]:
df['State'].value_counts()

CA    1224
NY    1015
TX     989
PA     831
FL     785
OH     588
IL     547
NJ     502
MI     499
NC     428
IN     428
MA     417
TN     404
VA     401
MN     375
GA     345
WA     341
WI     332
MO     319
MD     317
CO     249
KS     241
AZ     230
OR     224
OK     221
SC     206
NH     199
LA     193
AL     183
IA     158
MS     153
KY     139
CT     124
UT     121
ID     110
AR     105
NV     103
ME      86
NE      83
WV      72
MT      71
HI      62
NM      60
RI      59
DE      41
ND      31
WY      31
AK      28
SD      19
DC      18
VT      16
Name: State, dtype: int64

In [28]:
len(df['Metro'].value_counts())

701

In [29]:
len(df['CountyName'].value_counts())

1212

In [38]:
len(df['SizeRank'].value_counts()) # unique values only

14723

In [42]:
NY_df = df.loc[df['City'] == 'New York']
NY_df

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
6,61807,10467,New York,NY,New York,Bronx,7,152900.0,152700.0,152600.0,...,394400,400000,407300,411600,413200,414300,413900,411400,413200,417900
10,62037,11226,New York,NY,New York,Kings,11,162000.0,162300.0,162600.0,...,860200,851000,853900,870000,885100,887800,890500,901700,930700,963200
12,62087,11375,New York,NY,New York,Queens,13,252400.0,251800.0,251400.0,...,1022600,1033700,1048600,1066400,1081200,1088800,1092700,1089500,1084000,1084600
13,62045,11235,New York,NY,New York,Kings,14,190500.0,191000.0,191500.0,...,767300,777300,788800,793900,796000,799700,806600,810600,813400,816200
20,61625,10011,New York,NY,New York,New York,21,NaN,NaN,NaN,...,12137600,12112600,12036600,12050100,12016300,11946500,11978100,11849300,11563000,11478300
21,61703,10128,New York,NY,New York,New York,22,3676700.0,3704200.0,3729600.0,...,7410100,7422400,7417600,7427300,7371400,7342700,7353300,7350300,7363000,7386600
35,61802,10462,New York,NY,New York,Bronx,36,154300.0,154300.0,154400.0,...,432800,436100,439900,443500,444100,443900,446000,446400,447200,450200
36,61796,10456,New York,NY,New York,Bronx,37,NaN,NaN,NaN,...,357900,357100,356500,357200,362000,368500,374100,379800,388100,394400
46,61803,10463,New York,NY,New York,Bronx,47,180100.0,181000.0,181900.0,...,680800,684500,692000,700900,710200,726900,744500,757000,769400,778700
47,62040,11230,New York,NY,New York,Kings,48,230100.0,230800.0,231500.0,...,1079200,1082700,1082800,1084900,1091200,1102400,1120200,1141600,1170000,1195400
49,62020,11209,New York,NY,New York,Kings,50,255700.0,256600.0,257300.0,...,1005000,1013400,1019500,1024400,1024900,1018900,1023500,1029200,1023000,1015800
53,62023,11212,New York,NY,New York,Kings,54,125000.0,125000.0,125000.0,...,380000,387000,394600,401500,407900,414900,422300,426300,427100,428400
58,62025,11214,New York,NY,New York,Kings,59,191000.0,191200.0,191500.0,...,798000,805700,814200,820600,825000,826300,827600,830500,837300,844100
70,62032,11221,New York,NY,New York,Kings,71,133700.0,133700.0,133700.0,...,944500,948200,965300,984700,995000,998100,1000900,1015400,1037300,1048700
72,62039,11229,New York,NY,New York,Kings,73,183900.0,184200.0,184500.0,...,724100,730300,734500,735500,736100,741000,748100,755800,766200,775500
85,62088,11377,New York,NY,New York,Queens,86,179000.0,178900.0,179000.0,...,736400,739100,741900,745700,749100,749900,750300,753000,758200,762500
95,62044,11234,New York,NY,New York,Kings,96,172300.0,172100.0,171900.0,...,559400,563800,566400,565600,568700,575000,579400,583200,589400,593300
99,62067,11355,New York,NY,New York,Queens,100,182800.0,182500.0,182300.0,...,842400,847300,853000,859500,865500,871400,875900,877300,882400,890200
100,61790,10314,New York,NY,New York,Richmond,101,175800.0,175000.0,174200.0,...,515000,523500,527500,530200,534100,538900,543000,546200,550600,555600
106,62026,11215,New York,NY,New York,Kings,107,225700.0,227500.0,229400.0,...,2173600,2201100,2244400,2266100,2275800,2287100,2288900,2265300,2244900,2243900
117,62022,11211,New York,NY,New York,Kings,118,133200.0,132900.0,132500.0,...,1405100,1406400,1424700,1435300,1440500,1463100,1496100,1531100,1581900,1623700
138,62093,11385,New York,NY,New York,Queens,139,160600.0,160900.0,161300.0,...,623300,626100,629600,631300,631700,634200,639700,644700,651000,657500
140,62085,11373,New York,NY,New York,Queens,141,175400.0,175800.0,176400.0,...,743700,747200,754600,759800,762500,766900,773700,776100,775900,777000
156,62048,11238,New York,NY,New York,Kings,157,NaN,NaN,NaN,...,2673300,2696700,2716500,2724000,2744300,2768900,2810700,2848100,2869600,2885300
190,62043,11233,New York,NY,New York,Kings,191,124500.0,124500.0,124500.0,...,788800,788000,787100,797100,808400,809800,800800,806100,829200,852300
200,62046,11236,New York,NY,New York,Kings,201,160900.0,161000.0,161200.0,...,429500,434900,440900,443800,447800,453600,458400,461600,467200,472000
228,62084,11372,New York,NY,New York,Queens,229,190200.0,190800.0,191700.0,...,840100,845700,849300,849700,849400,845900,841900,848800,860100,861800
260,62029,11218,New York,NY,New York,Kings,261,177200.0,177000.0,176800.0,...,1201800,1195800,1199700,1201800,1198000,1186400,1174500,1173900,1196100,1220900
265,62034,11223,New York,NY,New York,Kings,266,207600.0,208000.0,208400.0,...,924500,930000,935800,941700,944700,947800,952100,966600,997000,1026600
272,61635,10021,New York,NY,New York,New York,273,NaN,NaN,NaN,...,18889900,18703500,18605300,18569400,18428800,18307100,18365900,18530400,18337700,17894900
308,62019,11208,New York,NY,New York,Kings,309,126800.0,126700.0,126700.0,...,432900,434400,437800,441600,440700,435400,429900,432300,442400,450600
356,62015,11204,New York,NY,New York,Kings,357,201100.0,201100.0,201100.0,...,921200,932800,946200,953800,957100,958900,963200,967900,972800,976400
366,62030,11219,New York,NY,New York,Kings,367,213200.0,212600.0,211900.0,...,1068200,1053000,1045400,1036700,1022900,1016000,1014400,1023800,1053000,1079600
407,62080,11368,New York,NY,New York,Queens,408,160700.0,160900.0,161100.0,...,695400,699300,705700,710300,714800,720700,727100,731400,734100,735400
423,62014,11203,New York,NY,New York,Kings,424,149000.0,149200.0,149400.0,...,450900,454600,458800,462800,468700,474500,475300,474800,481000,489900
439,62031,11220,New York,NY,New York,Kings,440,188500.0,188700.0,188800.0,...,893000,906100,918500,918400,909000,903000,906500,910700,915600,917900
475,62027,11216,New York,NY,New York,Kings,476,146100.0,146600.0,147200.0,...,1452000,1506100,1553100,1567700,1559700,1545700,1540200,1553600,1578400,1598700
508,61628,10014,New York,NY,New York,New York,509,NaN,NaN,NaN,...,9953900,9958800,9828700,9631000,9515800,9492800,9524900,9373400,9119600,8959300
552,62066,11354,New York,NY,New York,Queens,553,225300.0,226500.0,227800.0,...,872100,880900,892400,903100,911000,916500,923500,929900,935700,941200
612,61806,10466,New York,NY,New York,Bronx,613,156700.0,156600.0,156500.0,...,388900,394400,399800,404300,407700,410400,412200,414300,419300,424300
630,62086,11374,New York,NY,New York,Queens,631,215400.0,215600.0,215900.0,...,799900,802300,805200,808400,812300,817100,822600,827900,834200,839600
685,61813,10473,New York,NY,New York,Bronx,686,144600.0,145000.0,145400.0,...,386200,387400,392200,395800,396500,397800,400500,403000,407200,411800
700,62021,11210,New York,NY,New York,Kings,701,187300.0,187300.0,187200.0,...,777600,785800,792000,797600,800200,802900,809100,814500,816900,819600
743,62120,11434,New York,NY,New York,Queens,744,132900.0,132800.0,132800.0,...,400100,402500,404300,406200,408100,409500,410100,410600,412500,415400
811,62035,11224,New York,NY,New York,Kings,812,158000.0,157300.0,156700.0,...,477800,484900,490800,494400,496000,498700,502000,505600,511600,517900
836,61782,10306,New York,NY,New York,Richmond,837,178300.0,177600.0,176800.0,...,489100,496100,500200,503100,507000,512200,517100,522800,530900,538200
853,62179,11691,New York,NY,New York,Queens,854,155700.0,156000.0,156300.0,...,443000,446900,449500,449500,445400,440100,437700,440300,449600,460300
939,61809,10469,New York,NY,New York,Bronx,940,157200.0,157000.0,156700.0,...,412800,414500,416100,419300,419800,417300,413800,413600,419900,426100
960,61788,10312,New York,NY,New York,Richmond,961,180600.0,180100.0,179600.0,...,499500,504400,506400,506900,508700,513800,519700,524900,530100,535100
1026,61801,10461,New York,NY,New York,Bronx,1027,165900.0,165500.0,165100.0,...,464800,465800,468800,471600,471200,467900,463500,459000,461100,466500
1065,62009,11106,New York,NY,New York,New York,1066,164600.0,165300.0,165900.0,...,987400,995600,997600,1000800,1017900,1043900,1067100,1079200,1091000,1104300
1141,62118,11432,New York,NY,New York,Queens,1142,216000.0,216200.0,216500.0,...,764100,770800,778000,783600,791100,797000,798200,800500,810400,819400
1155,62033,11222,New York,NY,New York,Kings,1156,149200.0,148400.0,147500.0,...,1598000,1623800,1638700,1640400,1644100,1651200,1661800,1672800,1694000,1721100
1299,62004,11101,New York,NY,New York,Queens,1300,NaN,NaN,NaN,...,760100,739000,708300,698500,711200,742900,767300,769700,767200,782500
1413,61799,10459,New York,NY,New York,Bronx,1414,NaN,NaN,NaN,...,337200,334600,328700,332200,349300,370100,383000,393400,403900,410400
1434,62016,11205,New York,NY,New York,Kings,1435,NaN,NaN,NaN,...,2267400,2230800,2226800,2241400,2248400,2251000,2251600,2245300,2243700,2248400
1534,62028,11217,New York,NY,New York,Kings,1535,NaN,NaN,NaN,...,3405900,3442900,3443800,3426000,3407000,3404100,3413800,3482900,3588100,3656000
1557,62121,11435,New York,NY,New York,Queens,1558,136000.0,136300.0,136700.0,...,448500,453000,460500,465900,467500,468400,469500,471500,475800,480200
1906,62077,11365,New York,NY,New York,Queens,1907,224000.0,224200.0,224700.0,...,823100,829100,835600,841700,845100,845400,846000,849300,855700,861600
1931,62006,11103,New York,NY,New York,Queens,1932,182600.0,182400.0,182200.0,...,929800,927800,934600,945500,952900,948800,951200,956000,963500,969000
1980,62079,11367,New York,NY,New York,Queens,1981,189100.0,189100.0,189100.0,...,756000,764600,773800,783900,794000,801700,807400,810900,813300,815900
1995,62041,11231,New York,NY,New York,New York,1996,NaN,NaN,NaN,...,2926600,2946300,2958800,2965400,2964400,2961600,2965300,2974000,3004000,3044500
2043,62005,11102,New York,NY,New York,Queens,2044,168600.0,169500.0,170400.0,...,1013200,1015800,1010800,1008000,1027500,1053700,1071500,1072700,1088200,1112100
2088,61780,10304,New York,NY,New York,Richmond,2089,157500.0,157000.0,156500.0,...,481900,490300,495600,498800,502000,505600,509900,515700,523500,529800
2214,61777,10301,New York,NY,New York,Richmond,2215,175800.0,175500.0,175200.0,...,531500,539600,544900,543500,538900,536800,539300,542000,547300,552900
2497,62069,11357,New York,NY,New York,Queens,2498,248700.0,248000.0,247600.0,...,829700,838500,847600,854100,858600,863100,870000,878700,888500,896400
2532,61781,10305,New York,NY,New York,Richmond,2533,159200.0,158900.0,158600.0,...,480900,486600,489700,491900,494600,498700,503500,508400,514900,521600
2790,62008,11105,New York,NY,New York,Queens,2791,185700.0,186300.0,187000.0,...,911000,908900,911800,915900,912800,900800,897900,904900,918000,929200
2814,61805,10465,New York,NY,New York,Bronx,2815,172900.0,172900.0,172900.0,...,459500,462600,466500,472300,477300,480600,480700,479900,482700,485900
2845,62076,11364,New York,NY,New York,Queens,2846,244800.0,245200.0,245800.0,...,864000,869600,875000,880100,881400,878000,874600,875200,879600,884400
3183,62070,11358,New York,NY,New York,Queens,3184,228000.0,228400.0,228900.0,...,834500,841700,851200,860600,866000,868900,873700,877600,881400,885600
3198,62007,11104,New York,NY,New York,Queens,3199,177400.0,177500.0,177700.0,...,968200,971600,971800,969600,967700,965000,967400,973100,976900,976400
3728,62038,11228,New York,NY,New York,Kings,3729,219300.0,219600.0,219900.0,...,891500,895900,895700,894700,896400,902200,909000,912800,913900,915300
3785,62090,11379,New York,NY,New York,Queens,3786,192200.0,192800.0,193600.0,...,716000,719500,725200,729200,732100,735200,738600,740500,739600,738500
3996,62099,11413,New York,NY,New York,Queens,3997,153400.0,153800.0,154300.0,...,436600,438700,440500,442100,444300,445900,445900,444400,443600,444200
4228,62106,11420,New York,NY,New York,Queens,4229,139500.0,139900.0,140400.0,...,451300,457400,465300,471800,476600,479100,479800,481900,484600,486500
4335,62100,11414,New York,NY,New York,Queens,4336,258700.0,259500.0,260700.0,...,665200,666000,666400,667700,667900,667700,667400,666600,668100,669800
4500,61785,10309,New York,NY,New York,Richmond,4501,192600.0,192500.0,192600.0,...,553700,559700,563000,565900,569500,573300,576500,578600,580800,583400
4595,62073,11361,New York,NY,New York,Queens,4596,222900.0,224000.0,225300.0,...,831600,837100,842400,848600,853100,853600,854300,856600,860700,864100
4598,62098,11412,New York,NY,New York,Queens,4599,143500.0,143700.0,144000.0,...,437400,436100,436700,437900,436100,432300,430100,429200,430500,432900
4697,61811,10471,New York,NY,New York,Bronx,4698,317900.0,321900.0,325600.0,...,1022300,1044800,1068900,1089100,1100100,1120300,1145700,1156500,1158100,1164200
4820,62089,11378,New York,NY,New York,Queens,4821,174600.0,174300.0,174100.0,...,653600,661400,669100,674000,676400,678600,680200,683500,689500,696100
4829,62107,11421,New York,NY,New York,Queens,4830,145900.0,146000.0,146100.0,...,498100,504100,508200,513300,518900,523700,529400,536100,542700,547100
4962,62105,11419,New York,NY,New York,Queens,4963,145100.0,145200.0,145400.0,...,462500,466100,470400,474300,476000,476300,476500,480100,488500,497000
5066,62119,11433,New York,NY,New York,Queens,5067,125400.0,125500.0,125700.0,...,398900,397100,397200,400300,405800,412700,417200,420000,424900,431000
5073,62072,11360,New York,NY,New York,Queens,5074,292000.0,292400.0,293100.0,...,950300,957300,963000,965700,966400,965800,966900,973200,989700,1008100
5139,61784,10308,New York,NY,New York,Richmond,5140,176100.0,175400.0,174800.0,...,487400,491100,493200,495500,498000,501900,506700,512100,518400,524000
5164,62101,11415,New York,NY,New York,Queens,5165,225600.0,226500.0,227600.0,...,888200,908900,926600,937800,949800,959400,964200,965400,969000,976300
5185,62104,11418,New York,NY,New York,Queens,5186,164300.0,164300.0,164400.0,...,569400,576400,585100,592600,598700,602000,602600,603800,607600,611500
5572,62109,11423,New York,NY,New York,Queens,5573,157900.0,157900.0,158100.0,...,511700,513600,516800,520400,521900,522100,523600,526300,529800,533400
5718,62081,11369,New York,NY,New York,Queens,5719,160800.0,161100.0,161400.0,...,634600,641600,649300,653200,652200,651600,653700,658600,667300,675700
5732,61786,10310,New York,NY,New York,Richmond,5733,155600.0,155600.0,155600.0,...,453200,460500,466000,470800,474000,478100,483400,487900,494600,502700
5796,61779,10303,New York,NY,New York,Richmond,5797,129800.0,129400.0,129000.0,...,336700,341000,343000,345100,348900,353900,358400,363000,368600,374500
5826,62108,11422,New York,NY,New York,Queens,5827,160200.0,160100.0,160100.0,...,441100,443000,444400,446300,448900,450500,452100,453900,456700,459600
5840,62182,11694,New York,NY,New York,Queens,5841,285700.0,286600.0,287600.0,...,849400,860900,874400,880400,880900,885800,893000,896400,902900,912100
6068,62103,11417,New York,NY,New York,Queens,6069,155000.0,154900.0,155000.0,...,477100,480600,484100,487200,490100,494500,499400,503500,507100,510000
6134,62113,11427,New York,NY,New York,Queens,6135,177100.0,177200.0,177500.0,...,563700,566500,570800,574900,576300,576000,575700,576600,581400,587700
6354,62180,11692,New York,NY,New York,Queens,6355,119400.0,119200.0,119300.0,...,322500,322000,325300,326600,327200,332300,336600,340600,349300,356700
6463,62082,11370,New York,NY,New York,Queens,6464,180800.0,180800.0,181000.0,...,694200,707700,716700,719500,723700,727800,732900,740000,746500,749400
6554,62068,11356,New York,NY,New York,Queens,6555,182000.0,182000.0,182100.0,...,701600,708700,715200,722000,727300,731700,737700,744400,752900,761600
6922,62115,11429,New York,NY,New York,Queens,6923,147400.0,147500.0,147700.0,...,442100,443100,443900,444100,445000,447700,451500,455000,458400,461100
7066,62074,11362,New York,NY,New York,Queens,7067,266700.0,266900.0,267300.0,...,911900,923600,933900,941100,945100,950000,956700,961500,964400,967600
7135,62097,11411,New York,NY,New York,Queens,7136,161800.0,161800.0,162000.0,...,448200,449700,449900,450100,450700,451700,452000,449000,447400,449400
7145,61810,10470,New York,NY,New York,Bronx,7146,178600.0,177600.0,176600.0,...,442200,448900,451800,452900,456300,461600,466500,467500,466700,466000
7186,62112,11426,New York,NY,New York,Queens,7187,180200.0,180700.0,181400.0,...,566800,571800,578600,584000,585300,585200,586700,591500,598900,604400
7342,61778,10302,New York,NY,New York,Richmond,7343,135900.0,135600.0,135400.0,...,402200,404700,404100,403100,404600,407500,409400,410100,411900,414200
7427,62114,11428,New York,NY,New York,Queens,7428,154100.0,154200.0,154400.0,...,490400,493100,497000,501200,504400,507200,509500,511900,518500,526100
7724,61979,11004,New York,NY,New York,Queens,7725,215300.0,215300.0,215400.0,...,610400,614500,620700,625200,624300,619800,617700,620200,627200,634300
8007,62102,11416,New York,NY,New York,Queens,8008,142600.0,142700.0,142900.0,...,471600,476900,481500,486900,493200,498900,504900,509800,514000,517300
8008,62122,11436,New York,NY,New York,Queens,8009,119000.0,119400.0,119900.0,...,383800,382200,381000,382500,385600,387600,388700,390600,395100,400300
8303,62078,11366,New York,NY,New York,Queens,8304,231800.0,232000.0,232300.0,...,830000,839100,847800,854900,859600,861700,865600,871900,882700,893600
8387,61783,10307,New York,NY,New York,Richmond,8388,186700.0,186800.0,186900.0,...,522000,525600,527900,533800,543300,550800,559300,566900,571600,575900
9911,62075,11363,New York,NY,New York,Queens,9912,295000.0,296200.0,297700.0,...,1032000,1043700,1049800,1047900,1041200,1035400,1040700,1048600,1052100,1051300
11037,61804,10464,New York,NY,New York,Bronx,11038,195900.0,195600.0,195100.0,...,513100,518200,526100,532000,533100,533100,534400,533300,533000,536200

In [51]:
NY_df['CountyName'].value_counts()

Queens      55
Kings       28
Bronx       13
Richmond    12
New York     6
Name: CountyName, dtype: int64

In [43]:
# This function is provided with the starter notebook:
def melt_data(df):
    """
    Takes the zillow_data dataset in wide form or a subset of the zillow_dataset.  
    Returns a long-form datetime dataframe 
    with the datetime column names as the index and the values as the 'values' column.
    
    If more than one row is passes in the wide-form dataset, the values column
    will be the mean of the values from the datetime columns in all of the rows.
    """
    
    melted = pd.melt(df, id_vars=['RegionName', 'RegionID', 'SizeRank', 'City', 'State', 'Metro', 'CountyName'], var_name='time')
    melted['time'] = pd.to_datetime(melted['time'], infer_datetime_format=True)
    melted = melted.dropna(subset=['value'])
    return melted.groupby('time').aggregate({'value':'mean'})

In [44]:
long_df = melt_data(NY_df)

In [47]:
long_df.shape

(265, 1)

In [49]:
long_df

                   value
time
1996-04-01  2.148192e+05
1996-05-01  2.152337e+05
1996-06-01  2.156981e+05
1996-07-01  2.161865e+05
1996-08-01  2.167202e+05
1996-09-01  2.173125e+05
1996-10-01  2.179885e+05
1996-11-01  2.188394e+05
1996-12-01  2.199029e+05
1997-01-01  2.208837e+05
1997-02-01  2.215596e+05
1997-03-01  2.220519e+05
1997-04-01  2.225923e+05
1997-05-01  2.232529e+05
1997-06-01  2.239894e+05
1997-07-01  2.247788e+05
1997-08-01  2.256337e+05
1997-09-01  2.265702e+05
1997-10-01  2.276106e+05
1997-11-01  2.288519e+05
1997-12-01  2.302942e+05
1998-01-01  2.316183e+05
1998-02-01  2.325654e+05
1998-03-01  2.332942e+05
1998-04-01  2.340442e+05
1998-05-01  2.348904e+05
1998-06-01  2.357769e+05
1998-07-01  2.366808e+05
1998-08-01  2.376327e+05
1998-09-01  2.386423e+05
1998-10-01  2.397510e+05
1998-11-01  2.410635e+05
1998-12-01  2.425856e+05
1999-01-01  2.439875e+05
1999-02-01  2.450212e+05
1999-03-01  2.458865e+05
1999-04-01  2.468587e+05
1999-05-01  2.480087e+05
1999-06-01  2.493115e+05
1999-07-01  2.507298e+05
1999-08-01  2.522971e+05
1999-09-01  2.540019e+05
1999-10-01  2.558750e+05
1999-11-01  2.580529e+05
1999-12-01  2.605260e+05
2000-01-01  2.628885e+05
2000-02-01  2.648606e+05
2000-03-01  2.666673e+05
2000-04-01  2.685837e+05
2000-05-01  2.706923e+05
2000-06-01  2.729548e+05
2000-07-01  2.753269e+05
2000-08-01  2.777865e+05
2000-09-01  2.803394e+05
2000-10-01  2.830135e+05
2000-11-01  2.859923e+05
2000-12-01  2.892250e+05
2001-01-01  2.921942e+05
2001-02-01  2.946375e+05
2001-03-01  2.968769e+05
2001-04-01  2.992442e+05
2001-05-01  3.018173e+05
2001-06-01  3.045673e+05
2001-07-01  3.074067e+05
2001-08-01  3.103231e+05
2001-09-01  3.133308e+05
2001-10-01  3.164087e+05
2001-11-01  3.197913e+05
2001-12-01  3.233019e+05
2002-01-01  3.263365e+05
2002-02-01  3.286231e+05
2002-03-01  3.305654e+05
2002-04-01  3.325288e+05
2002-05-01  3.346913e+05
2002-06-01  3.370212e+05
2002-07-01  3.394385e+05
2002-08-01  3.419827e+05
2002-09-01  3.447317e+05
2002-10-01  3.479846e+05
2002-11-01  3.499087e+05
2002-12-01  3.516673e+05
2003-01-01  3.565298e+05
2003-02-01  3.654212e+05
2003-03-01  3.753750e+05
2003-04-01  3.846356e+05
2003-05-01  3.918240e+05
2003-06-01  3.973596e+05
2003-07-01  3.999638e+05
2003-08-01  4.034762e+05
2003-09-01  4.063314e+05
2003-10-01  4.088695e+05
2003-11-01  4.117038e+05
2003-12-01  4.148486e+05
2004-01-01  5.999577e+05
2004-02-01  5.888955e+05
2004-03-01  5.793108e+05
2004-04-01  5.713712e+05
2004-05-01  5.653991e+05
2004-06-01  5.616189e+05
2004-07-01  5.608766e+05
2004-08-01  5.638270e+05
2004-09-01  5.704856e+05
2004-10-01  5.796973e+05
2004-11-01  5.906171e+05
2004-12-01  6.022757e+05
2005-01-01  6.414688e+05
2005-02-01  6.527929e+05
2005-03-01  6.636455e+05
2005-04-01  6.735473e+05
2005-05-01  6.816491e+05
2005-06-01  6.884938e+05
2005-07-01  6.953304e+05
2005-08-01  7.030848e+05
2005-09-01  7.120812e+05
2005-10-01  7.219518e+05
2005-11-01  7.326991e+05
2005-12-01  7.440562e+05
2006-01-01  7.547536e+05
2006-02-01  7.637205e+05
2006-03-01  7.717241e+05
2006-04-01  7.788848e+05
2006-05-01  7.841312e+05
2006-06-01  7.864250e+05
2006-07-01  7.849973e+05
2006-08-01  7.801116e+05
2006-09-01  7.729402e+05
2006-10-01  7.655330e+05
2006-11-01  7.603446e+05
2006-12-01  7.586384e+05
2007-01-01  7.594598e+05
2007-02-01  7.611679e+05
2007-03-01  7.636205e+05
2007-04-01  7.660857e+05
2007-05-01  7.670098e+05
2007-06-01  7.666268e+05
2007-07-01  7.678643e+05
2007-08-01  7.724848e+05
2007-09-01  7.796223e+05
2007-10-01  7.868741e+05
2007-11-01  7.930455e+05
2007-12-01  7.976562e+05
2008-01-01  8.003536e+05
2008-02-01  8.006964e+05
2008-03-01  8.002750e+05
2008-04-01  7.992616e+05
2008-05-01  7.958964e+05
2008-06-01  7.901643e+05
2008-07-01  7.852652e+05
2008-08-01  7.826045e+05
2008-09-01  7.808938e+05
2008-10-01  7.786652e+05
2008-11-01  7.761241e+05
2008-12-01  7.740312e+05
2009-01-01  7.724545e+05
2009-02-01  7.706821e+05
2009-03-01  7.696062e+05
2009-04-01  7.690875e+05
2009-05-01  7.669411e+05
2009-06-01  7.624750e+05
2009-07-01  7.584482e+05
2009-08-01  7.567688e+05
2009-09-01  7.573143e+05
2009-10-01  7.590848e+05
2009-11-01  7.616491e+05
2009-12-01  7.643643e+05
2010-01-01  7.664223e+05
2010-02-01  7.688455e+05
2010-03-01  7.676643e+05
2010-04-01  7.631446e+05
2010-05-01  7.634902e+05
2010-06-01  7.710723e+05
2010-07-01  7.776902e+05
2010-08-01  7.772286e+05
2010-09-01  7.716973e+05
2010-10-01  7.693973e+05
2010-11-01  7.687955e+05
2010-12-01  7.668027e+05
2011-01-01  7.656473e+05
2011-02-01  7.684134e+05
2011-03-01  7.710875e+05
2011-04-01  7.731473e+05
2011-05-01  7.752232e+05
2011-06-01  7.776232e+05
2011-07-01  7.780911e+05
2011-08-01  7.778080e+05
2011-09-01  7.797911e+05
2011-10-01  7.807920e+05
2011-11-01  7.800384e+05
2011-12-01  7.773795e+05
2012-01-01  7.723336e+05
2012-02-01  7.701434e+05
2012-03-01  7.680788e+05
2012-04-01  7.652761e+05
2012-05-01  7.650850e+05
2012-06-01  7.663637e+05
2012-07-01  7.671265e+05
2012-08-01  7.665035e+05
2012-09-01  7.667805e+05
2012-10-01  7.676027e+05
2012-11-01  7.719478e+05
2012-12-01  7.769283e+05
2013-01-01  7.795345e+05
2013-02-01  7.804389e+05
2013-03-01  7.848832e+05
2013-04-01  7.916752e+05
2013-05-01  7.984947e+05
2013-06-01  8.060035e+05
2013-07-01  8.132619e+05
2013-08-01  8.208372e+05
2013-09-01  8.283195e+05
2013-10-01  8.373460e+05
2013-11-01  8.449735e+05
2013-12-01  8.567035e+05
2014-01-01  8.630044e+05
2014-02-01  8.724965e+05
2014-03-01  8.839140e+05
2014-04-01  8.989096e+05
2014-05-01  9.102877e+05
2014-06-01  9.160456e+05
2014-07-01  9.239000e+05
2014-08-01  9.367474e+05
2014-09-01  9.509333e+05
2014-10-01  9.606254e+05
2014-11-01  9.691053e+05
2014-12-01  9.767588e+05
2015-01-01  9.864596e+05
2015-02-01  9.983026e+05
2015-03-01  1.007794e+06
2015-04-01  1.014125e+06
2015-05-01  1.020391e+06
2015-06-01  1.030045e+06
2015-07-01  1.041642e+06
2015-08-01  1.052292e+06
2015-09-01  1.059963e+06
2015-10-01  1.066317e+06
2015-11-01  1.070582e+06
2015-12-01  1.074268e+06
2016-01-01  1.078186e+06
2016-02-01  1.081475e+06
2016-03-01  1.082323e+06
2016-04-01  1.084232e+06
2016-05-01  1.087615e+06
2016-06-01  1.089489e+06
2016-07-01  1.092178e+06
2016-08-01  1.100596e+06
2016-09-01  1.110084e+06
2016-10-01  1.117001e+06
2016-11-01  1.122597e+06
2016-12-01  1.127429e+06
2017-01-01  1.132304e+06
2017-02-01  1.136111e+06
2017-03-01  1.141875e+06
2017-04-01  1.151324e+06
2017-05-01  1.159282e+06
2017-06-01  1.162566e+06
2017-07-01  1.166365e+06
2017-08-01  1.170039e+06
2017-09-01  1.172875e+06
2017-10-01  1.175287e+06
2017-11-01  1.175530e+06
2017-12-01  1.176734e+06
2018-01-01  1.182094e+06
2018-02-01  1.185925e+06
2018-03-01  1.187463e+06
2018-04-01  1.189456e+06

In [53]:
new_zillow_df = pd.read_csv('../Data/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
new_zillow_df.head(3)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,322791.0,...,1098893.0,1107554.0,1116367.0,1126666.0,1131034.0,1130418.0,1130985.0,1136847.0,1148541.0,1167157.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,312893.0,...,512225.0,516042.0,520532.0,523117.0,525702.0,528495.0,530491.0,531877.0,532090.0,534766.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,503959.0,...,1458014.0,1459861.0,1474220.0,1489954.0,1498567.0,1502806.0,1503119.0,1513679.0,1523377.0,1540289.0

In [55]:
new_zillow_df['City'].value_counts()

New York           178
Houston            106
Los Angeles        100
Chicago             56
San Antonio         55
                  ...
Blissfield           1
Igo                  1
Seibert              1
Daykin               1
Washingtonville      1
Name: City, Length: 13886, dtype: int64